apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-and-deploy-run
  namespace: default
spec:
  pipelineRef:
    name: build-and-deploy
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: pvc-claim
    - name: dockerconfig
      secret:
        secretName: kaniko-secret
  params:
    - name: CONSUMER_IMAGE
      value: wong801/web-consumer:latest
    - name: SERVICE_IMAGE
      value: wong801/web-service:latest
